# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: YOUR_DB_NAME_HERE
      POSTGRES_PASSWORD: password
      ENVIRONMENT: development
    ports:
      - "5432:5432"
    volumes:
      # load example data
      - ./test_data:/docker-entrypoint-initdb.d
